notifications:
  email:
    on_success: always # default: change
    on_failure: always # default: always

sudo: required

services:
  - docker

script:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -f Dockerfile -t eifinger/rpi-docker-tensorflow-1.11 .
  - docker push eifinger/rpi-docker-tensorflow-1.11
